# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_text_edit_dialog_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MyTextEditDialog(object):
    def setupUi(self, MyTextEditDialog):
        MyTextEditDialog.setObjectName("MyTextEditDialog")
        MyTextEditDialog.resize(631, 233)
        font = QtGui.QFont()
        font.setFamily("BIZ UDPゴシック")
        MyTextEditDialog.setFont(font)
        self.gridLayout_4 = QtWidgets.QGridLayout(MyTextEditDialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_3 = QtWidgets.QFrame(MyTextEditDialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setContentsMargins(5, 5, 5, 5)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(67, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.label_sub = QtWidgets.QLabel(self.frame_3)
        self.label_sub.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_sub.setFont(font)
        self.label_sub.setText("")
        self.label_sub.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sub.setObjectName("label_sub")
        self.gridLayout_3.addWidget(self.label_sub, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(MyTextEditDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_main = QtWidgets.QTextEdit(self.frame)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(13)
        self.textEdit_main.setFont(font)
        self.textEdit_main.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit_main.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textEdit_main.setAcceptRichText(False)
        self.textEdit_main.setObjectName("textEdit_main")
        self.gridLayout.addWidget(self.textEdit_main, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 1, 0, 1, 1)

        self.retranslateUi(MyTextEditDialog)
        QtCore.QMetaObject.connectSlotsByName(MyTextEditDialog)

    def retranslateUi(self, MyTextEditDialog):
        _translate = QtCore.QCoreApplication.translate
        MyTextEditDialog.setWindowTitle(_translate("MyTextEditDialog", "テキストの編集"))
        self.label.setText(_translate("MyTextEditDialog", "テキストを編集してエンターキーで確定"))
