# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test2_sub.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 537)
        font = QtGui.QFont()
        font.setFamily("BIZ UDゴシック")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 361, 201))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_1 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.verticalLayout_1 = QtWidgets.QVBoxLayout(self.frame_1)
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.label_img = QtWidgets.QLabel(self.frame_1)
        self.label_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_img.setObjectName("label_img")
        self.verticalLayout_1.addWidget(self.label_img)
        self.label_text = QtWidgets.QLabel(self.frame_1)
        self.label_text.setFrameShape(QtWidgets.QFrame.Box)
        self.label_text.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_text.setObjectName("label_text")
        self.verticalLayout_1.addWidget(self.label_text)
        self.verticalLayout_1.setStretch(0, 1)
        self.horizontalLayout.addWidget(self.frame_1)
        self.frame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_up = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_up.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_up.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_up.setObjectName("pushButton_up")
        self.verticalLayout_3.addWidget(self.pushButton_up)
        self.pushButto_down = QtWidgets.QPushButton(self.frame_2)
        self.pushButto_down.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButto_down.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButto_down.setObjectName("pushButto_down")
        self.verticalLayout_3.addWidget(self.pushButto_down)
        self.horizontalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 425, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_img.setText(_translate("MainWindow", "ImgLabel"))
        self.label_text.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_up.setText(_translate("MainWindow", "↑"))
        self.pushButto_down.setText(_translate("MainWindow", "↓"))
